repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: name-tests-test
      - id: mixed-line-ending
      - id: fix-encoding-pragma
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: debug-statements
      - id: check-yaml
      - id: check-xml
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-ast
      - id: check-added-large-files
        exclude: data/excel_analysis/mill/mill_output_template.xlsx|data/excel_analysis/contract/sensitivity_check_temp.xlsx|data/test_fixtures/.
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
      - id: python-safety-dependencies-check
        # TODO: Remove when SQLAlchemy patch is released.
        args: ["--ignore=51668"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.0
    hooks:
      - id: dockerfile_lint
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/ambv/black
    rev: "22.12.0"
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: ["click==8.0.4"]
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-blind-except==0.2.*",
            "flake8-bugbear==23.1.*",
            "flake8-builtins==2.1.*",
            "flake8-comprehensions==3.10.*",
            "flake8-debugger==4.1.*",
            "flake8-docstrings==1.7.*",
            "flake8-logging-format==0.9.*",
            "flake8-module-name==0.2.*",
            "flake8-print==5.0.*",
            "flake8_commas==2.1.*",
          ]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: shellcheck
        additional_dependencies: []
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
        additional_dependencies:
          [
            "types-python-dateutil==2.8.*",
            "types-PyYAML==6.0.*",
            "types-requests==2.28.*",
            "types-simplejson==3.18.*",
          ]
        exclude: 'setup\.py' # mypy does not handle multiple setup.py files very well.


  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        args: [
          "--python-folders",
          "flight_tower",
        ]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.3.2
    hooks:
      - id: sqlfluff-fix
      - id: sqlfluff-lint
