* Generated by MPModelProtoExporter
*   Name             :
*   Format           : Free
*   Constraints      : 2
*   Variables        : 2
*     Binary         : 0
*     Integer        : 1
*     Continuous     : 1
NAME
OBJSENSE
  MAX
ROWS
 N  COST
 L  auto_c_000000000
 L  auto_c_000000001
COLUMNS
  INTSTART  'MARKER'                            'INTORG'
    x                 COST                   3  auto_c_000000000       1
    x                 auto_c_000000001       1
  INTEND    'MARKER'                            'INTEND'
    z                 COST                   2  auto_c_000000000      -1
    z                 auto_c_000000001       1
RHS
    RHS               auto_c_000000000       5  auto_c_000000001       9
BOUNDS
 LI BOUND             x                      0
 PL BOUND             z
ENDATA
